### ISSUE TITLE
Panel Height doesn't listen for body height changes

### ISSUE THREAD

**Issue by AlaaEldeenYsr** [BendixMa/sliding-sheet#18]
On the first layout the panel take its initial height based on the body height, But after then if happened any changes to the body height the panel doesn't listen for that, its height doesn't get changed to fit the new body height after change, Panel height keep fixed with the initial layout height,

Gif for the issue
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/52201392/78036815-07eeb200-736b-11ea-8804-07b7aa6e50a7.gif)

I think this example is very useful in this case, There is an apis in flutter for listening to widgets sizes changes.
```
class SizeChangedReactivityWidget extends StatefulWidget {
  @override
  _SizeChangedReactivityWidgetState createState() => _SizeChangedReactivityWidgetState();
}

class _SizeChangedReactivityWidgetState extends State<SizeChangedReactivityWidget> {
  final key = GlobalKey();
  var counter = 0;

  @override
  Widget build(BuildContext context) {
    return NotificationListener<SizeChangedLayoutNotification>(
      onNotification: (notification) {
        print('New Height is' + key.currentContext.size.height.toString());
        return true;
      },
      child: SizeChangedLayoutNotifier(
        key: key,
        child: Column(children: <Widget>[
          ...Iterable.generate(counter, (i) => Text('Item Number $i')),
          FlatButton(
            onPressed: () => setState(() => counter++),
            child: Text('Add New Item To Change Body Height'),
          ),
        ]),
      ),
    );
  }
}

```

Gif for the wanted behavior
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/52201392/78037654-20130100-736c-11ea-8b2a-b922f779e900.gif)

**Comment by BendixMa** [comment]
Can you replace the dependency to 
~~~yaml
sliding_sheet:
    git:
      url: https://github.com/BendixMa/sliding-sheet
~~~
and checkout if it works now as you'd expect?

The sheet should now rebuild itself when the size of on of its children changes and if it is not currently snapped at a snapping point from the `snappings` list, the sheet should move to the closest snap.

**Comment by AlaaEldeenYsr** [comment]
Alright it's working well now thank you, I think it well be nice if you provided a parameter for a max height

**Comment by AlaaEldeenYsr** [comment]
And also a simple duration transition for height changes will be nice

**Comment by BendixMa** [comment]
> Alright it's working well now thank you, I think it well be nice if you provided a parameter for a max height

The max Height will be the last snap you provide to the `snappings` array on the `SnapSpec` or what do you mean with `maxHeight`?

> And also a simple duration transition for height changes will be nice

Do you mean a transition when the height of the sheet changes because the childs height changed?

**Comment by AlaaEldeenYsr** [comment]
i mean with max height that the panel stop to listen for bdy height changes on a specific height like this
![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/52201392/78054128-e0571400-7381-11ea-9496-6f036088ab32.gif)

**Comment by AlaaEldeenYsr** [comment]
Wait i can handle this easy with a ConstrainedBox max height, So sorry forget it

**Comment by AlaaEldeenYsr** [comment]
> Do you mean a transition when the height of the sheet changes because the childs height changed?

Yes because as you see the height changes reflects a rapid movement as you see in the Gif, you can notice this if you focused on the bottom line of the panel, So it will be nice if this rapid movement handled with a simple duration transition.
![ezgif com-video-to-gif (4)](https://user-images.githubusercontent.com/52201392/78055994-ae937c80-7384-11ea-8257-2e22f334644e.gif)

But this is like an extra feature you can consider the issue solved here.

**Comment by BendixMa** [comment]
Yeah I'll think about it, although I think that this should usually be the responsibility of the child, not the sheet. You could for example try to wrap the `Column` or `List`or whatever you're using inside an `AnimatedSize` or `AnimatedContainer`, however I'll think about it.

I published the current version now on pub (0.2.12) so you can remove the Github dependency if you want. Feel free to open issues when you find something again that ain't workin hahah.

**Comment by AlaaEldeenYsr** [comment]
@BendixMa Thank you very much bro

**Comment by P-B1101** [comment]
I actually still have this problem. in my case when I remove one item from list in sheet, it's height won't resize until i change touch the sheet or change it's snap programmatically. and if I do that it will visible as a glitch in the screen.
